<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_ProductAttechment
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
/**
 * @var \Mavenbird\ProductAttachment\Block\Order\Email\Attachments $block
 */
if ($attachments = $block->getAttachments()):
    ?>
        <br><b><?= $escaper->escapeHtml($block->getBlockTitle()); ?></b>
        <?php foreach ($attachments as $attachment): ?>
            <p><a href="<?= $escaper->escapeUrl($attachment->getFrontendUrl()); ?>" target="_blank"><?= $escaper->escapeHtml($attachment->getLabel()); ?></a></p>
        <?php endforeach; ?>
<?php endif; ?>
