<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_ProductAttechment
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
/** @var $block \Mavenbird\ProductAttachment\Block\Adminhtml\Widget\FileRows */
?>
<style>
    .file.admin__control-table td{
        vertical-align: middle!important;
    }
</style>

<div id="manage-options-panel">
    <table class="admin__control-table">
        <thead>
        <tr id="attribute-options-table">
            <th class="col-draggable"></th>
            <th><?= $escaper->escapeHtml(__('ID')); ?></th>
            <th><?= $escaper->escapeHtml(__('File Name')); ?></th>
            <th><?= $escaper->escapeHtml(__('File Label')); ?></th>
            <th class="col-delete"><?= $escaper->escapeHtml(__('Remove')); ?></th>
        </tr>
        </thead>
        <tbody data-role="options-container" class="ignore-validate"></tbody>
    </table>
    <input type="hidden" id="option-count-check" value="" />
</div>

<script>
    require(['jquery'], function($) {
        //TODO check sesurity
        var fSet = '<?= $escaper->escapeHtml($block->getFieldsetId()); ?>';
        $(document).on('change', '.field-' + fSet + '_widget_type select', function() {
            $('.field-' + fSet + '_files, .field-' + fSet + '_category, .field-' + fSet + '_product').hide()
                .next().hide();

            switch ($(this).val()) {
                case '<?= (int)\Mavenbird\ProductAttachment\Model\SourceOptions\WidgetType::SPECIFIC_CATEGORY ?>':
                    $('.field-' + fSet + '_category').show().next().show();
                    break;
                case '<?= (int)\Mavenbird\ProductAttachment\Model\SourceOptions\WidgetType::SPECIFIC_PRODUCT ?>':
                    $('.field-' + fSet + '_product').show().next().show();
                    break;
                case '<?= (int)\Mavenbird\ProductAttachment\Model\SourceOptions\WidgetType::CUSTOM_FILES ?>':
                    $('.field-' + fSet + '_files').show().next().show();
                    break;
            }
        });
        $('.field-' + fSet + '_widget_type select').change();
    });
    require(['Mavenbird_ProductAttachment/js/dynamic-rows/filesrows'], function(filesRows){
        filesRows({
            "filesData": <?= /* @escapeNotVerified */ json_encode($block->getFiles()); ?>,
            "isSortable":  true,
            "isReadOnly": false,
            "uniqId": "<?= $escaper->escapeHtml($block->getUniqId()); ?>",
            "template": "<tr>\n" +
            "        <td class=\"col-draggable\">\n" +
            "            <div data-role=\"draggable-handle\" class=\"draggable-handle\"\n" +
            "                 title=\"<?= $escaper->escapeHtml(__('Sort Option')); ?>\"></div>\n" +
            "            <input data-role=\"order\" type=\"hidden\" name=\"option[order][<%- data.file_id %>]\"\n" +
            "                   data-file-id =\"<%- data.file_id %>\" value=\"<%- data.order %>\" />\n" +
            "        </td>\n" +
            "        <td class=\"col-file-id\"><%- data.file_id %></td>\n" +
            "        <td class=\"col-file-id\"><%- data.filename %></td>\n" +
            "        <td class=\"col-file-id\"><%- data.label %></td>\n" +
            "        <td id=\"delete_button_container_<%- data.file_id %>\" class=\"col-delete\">\n" +
            "            <button title=\"<?= $escaper->escapeHtml(__('Delete')); ?>\" type=\"button\"\n" +
            "                    class=\"action-delete\">\n" +
            "                <span><?= $escaper->escapeHtml(__('Delete')); ?></span>\n" +
            "            </button>\n" +
            "        </td>\n" +
            "    </tr>"
        });
    });

</script>
