<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_ProductAttechment
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
/**
 * @var \Mavenbird\ProductAttachment\Block\Order\View\Attachments $block
 */
if ($attachments = $block->getAttachments()):
    ?>
<div class="widget attachments attachments-order-view">
    <b><?= $escaper->escapeHtml($block->getBlockTitle()); ?></b>
        <?php foreach ($attachments as $attachment): ?>
            <div class="fileline">
                <?php if ($block->isShowIcon() && $attachment->getIconUrl()): ?>
                    <img src="<?= $escaper->escapeUrl($attachment->getIconUrl()) ?>" class="fileicon" />
                <?php endif; ?>

                <a href="<?= $escaper->escapeUrl($attachment->getFrontendUrl()) ?>" class="filelink" target="_blank">
                    <?= $escaper->escapeHtml($attachment->getLabel()); ?>
                </a>

                <?php if ($block->isShowFilesize() && $attachment->getFileSize()): ?>
                    <span class="filesize">(<?= $escaper->escapeHtml($attachment->getReadableFileSize()) ?>)</span>
                <?php endif ?>
            </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
