<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_ProductAttechment
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function($) {
            //<![CDATA[
            var entity = $('#entity');
            entity.hide();
            entity.closest('fieldset').find('label.label.admin__field-label').css('visibility','hidden');
            $(entity).val('file_files_import');
            varienImport.handleEntityTypeSelector();
            $('#sample-file-link').attr('href', '<?= $escaper->escapeUrl($block->getGenerateUrl()) ?>');
            //]]>
        }
    );
</script>

<script>
    require(['jquery', 'mage/translate'], function ($, $t) {
        $('#sample-file-link').text($t('Generate Import File'));
        var Interval = setInterval(function() {
            if (!$('#edit_form').is(':visible')) {
                $('.action-next-step').attr('disabled', false);
                $('.action-next-step').click(function () {
                    location.href='<?= $escaper->escapeUrl($block->getFinishLink()); ?>';
                });

                $('.action-next-step').find('span').text($t('Finish'));
                $('.action-back-step').hide();
                $('.action-wrap .action-cancel').hide();
                clearInterval(Interval);
            }
        }, 500);
    })
</script>