<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_ProductAttechment
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<div class="steps-wizard file-steps-wizard">
    <div data-role="steps-wizard-controls" class="steps-wizard-navigation">
        <ul class="nav-bar">
            <?php foreach ($block->getSteps() as $step => $caption) { ?>
                <li data-role="collapsible" data-bind="css: { 'active': <?= ($step === $block->getCurrentStep() ? 'true' : 'false') ?>}">
                    <a href="#">
                        <?= $escaper->escapeHtml(__($caption)) ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
        <div class="nav-bar-outer-actions">
                <div class="action-wrap" data-role="closeBtn">
                    <button type="button"
                            class="action-cancel action-tertiary" onclick="location.href = '<?= $escaper->escapeUrl($block->getImportListingUrl()) ?>'">
                        <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                    </button>
                </div>
            <div class="action-wrap action-wrap-prev" data-role="step-wizard-prev">
                <button type="button"
                        class="action-default action-back-step"
                        <?= ($block->getBackLink() ? '' : 'disabled="true"') ?>
                        <?= ($block->getBackLink() ? 'onclick="location.href=\'' . $escaper->escapeUrl($block->getBackLink()) . '\'"' : '') ?>>
                    <span><?= /* @escapeNotVerified */  __('Back') ?></span>
                </button>
            </div>
            <div class="action-wrap action-wrap-next" data-role="step-wizard-next">
                <button type="button"
                        class="action-default action-primary action-next-step save"
                        id="save"
                        data-ui-id="save-button"
                        <?= ($block->getNextLink() ? '' : 'disabled="true"') ?>
                        <?= ($block->getNextLink() ? 'onclick="location.href=\'' . $escaper->escapeUrl($block->getNextLink()) . '\'"' : '') ?>>
                    <span><?= /* @escapeNotVerified */  __('Next') ?></span>
                </button>
            </div>
        </div>
    </div>
    </div>
